language: python
python:
- "3.4"
- "3.5"
- "3.6"
before_install:
- "pip install -U pip"
- "python setup.py install"
# command to install dependencies
install:
- pip install -U -r requirements.txt
# command to run tests
script:
- coverage run -m pytest
# run coverage
after_success:
- codecov
