language: python
python:
- "3.4"
- "3.5"
- "3.6"
before_install:
- "pip install -U pip"
- "python setup.py build"
- "python setup.py install"
- "python setup.py clean"
# command to install dependencies
install:
- pip install -r requirements.txt
# command to run tests
script:
- pytest

